captcha:
    height: 80
    width: 240
    length: 6
    max_skew: 0.7
    dot_count: 80
email:
    host: smtp.qq.com
    port: 465
    from: 2454919667@qq.com
    nickname: xiaoxin
    secret: wtvnrsorjejcdjhi
    is_ssl: true
es:
    url: http://127.0.0.1:9200
    username: ""
    password: ""
    is_console_print: true
gaode:
    enable: true
    key: 3e448832039c28792a42ec7c42c12d34
jwt:
    access_token_secret: 1CPKVgqSv7evK84l78aqAAMRSSJTVCUGcmH85l7SpFA=
    refresh_token_secret: RQfh52utH9IWYwybg15JFt_IrZAYVFwkONRYAuucRq4=
    access_token_expiry_time: 2h
    refresh_token_expiry_time: 7d
    issuer: go_blog
mysql:
    host: 127.0.0.1
    port: 3306
    config: charset=utf8mb4&parseTime=True&loc=Local
    db_name: blog_db
    username: root
    password: root
    max_idle_conns: 10
    max_open_conns: 100
    log_mode: info
qiniu:
    zone: z0
    bucket: go-blog-images
    img_path: https://tirc1hsbz.hb-bkt.clouddn.com
    access_key: xiTV0hNtCefPFHMpQHGTnx4ZYOqcONMjj9QKrsmP
    secret_key: FYnDdhXPzE3EH4OA8RspRqvc-P-P1NODQMEjtZuP
    use_https: true
    use_cdn_domains: true
qq:
    enable: false
    app_id: "000000000"
    app_key: xxxxxxxxxxxxxxxx
    redirect_uri: http://xxx.xxx/xxx
redis:
    address: 127.0.0.1:6379
    password: ""
    db: 0
system:
    host: 0.0.0.0
    port: 8080
    env: release
    router_prefix: api
    use_multipoint: true
    sessions_secret: s0AdOEYUibVdnCVImPaS1NWBzH_KeHeBCHquqm17dpk=
    oss_type: local
upload:
    size: 20
    path: uploads
website:
    logo: ""
    full_logo: ""
    title: 心之所想
    slogan: 心之所想
    slogan_en: Follow Your Heart
    description: 随时随地分享你的想法
    version: 1.0.0
    created_at: "2026-1-15"
    icp_filing: icp备案号
    public_security_filing: 公安备案号
    bilibili_url: https://space.bilibili.com/3494363720059293
    github_url: https://github.com/xiaoxin186/go_blog
    name: xiaoxin
    job: golang后端开发
    address: 北京
    email: 2454919667@qq.com
    qq_image: /uploads/image/19162bca823aeb32e7cedb7defb24e3e-20260727084523.jpg
    wechat_image: ""
zap:
    level: info
    filename: log/go_blog.log
    max_size: 200
    max_backups: 30
    max_age: 5
    is_console_print: true
